services:
  flask_app:
    build: .
    image: portfolio_app
    container_name: portfolio_container
    networks:
      - app_network
    volumes:
      - .:/app
    expose:
      - "8002"

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    networks:
      - app_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  app_network:
    driver: bridge
